CREATE TABLE COLONIA(
    ID_COLONIA NUMBER PRIMARY KEY NOT NULL, 
    NOMBRE NVARCHAR2(100)
);

-- TABLA DUEÑO
CREATE TABLE COLONIA(
    ID_DUENIO NUMBER PRIMARY KEY NOT NULL, 
    NOMBRE NVARCHAR2(100), 
    APELLIDOS NVARCHAR2(100),
    DIRECCION NVARCHAR2(100)
);

CREATE TABLE RAZA(
    ID_RAZA NUMBER PRIMARY KEY NOT NULL,
    NOMBRE NVARCHAR2(100),
    PAIS_ORIGEN NVARCHAR2(100)
);

-- TABLA MASCOTA
CREATE TABLE MASCOTA(
    ID_MASCOTA NUMBER PRIMARY KEY NOT NULL,
    NOMBRE NVARCHAR2(100),
    FECHA_NAC  DATE,
    ID_DUENIO NUMBER,
    ID_RAZA NUMBER,
    CONSTRAINT FK_DUENIO_MASCOTA FOREIGN KEY (DUENIO_ID) REFERENCES DUENIO(ID_DUENIO),
    CONSTRAINT FK_RAZA_MASCOTA FOREIGN KEY (RAZA_ID) REFERENCES RAZA(ID_RAZA)
);

-- AGREGAR COLUMNA
ALTER TABLE MASCOTA
ADD FECHA_REGISTRO DATE; 
ALTER TABLE MASCOTA
ADD FECHA_ULTIMA_MODIFICACION DATE;

--AGREGAR LLAVE FORANEA
ALTER TABLE DUENIO
ADD FOREIGN KEY (ID_COLONIA) REFERENCES COLINA(ID_COLONIA);

--RENOMBRR COLUMNA 
ALTER TABLE MASCOTA
RENAME COLUMN DUENIO_ID TO ID_DUENIO;

ALTER TABLE MASCOTA
RENAME COLUMN RAZA_ID TO ID_RAZA;

--MODIFICAR VALOR DE UNA COLUMNA
ALTER TABLE MASCOTA MODIFY FECHA_NAC DATE; 




